# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0005_remove_user_avatar'),
        ('notice', '0002_auto_20170517_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletin',
            name='follower',
        ),
        migrations.AddField(
            model_name='bulletin',
            name='follower',
            field=models.ManyToManyField(related_name='bulletin_follower', to='user_manage.User'),
        ),
    ]
