# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-14 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='security_answer',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='security_question',
            field=models.CharField(default='', max_length=256),
        ),
    ]
