# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(default="static '/img/icon.png'", max_length=256),
        ),
    ]
